import unittest
from vigenere_cracker import decrypt, encrypt, ascii_string_to_hex_array


class DecryptTest(unittest.TestCase):
    def test_special_characters(self):
        message = 'a secret-message}+123!.?<>,.=-)(!@#$%^&*'
        key = ''.join(ascii_string_to_hex_array('secret'))
        encrypted = encrypt(message, key)

        expected = decrypt(encrypted, key)

        self.assertEqual(message, expected)

    def test_long_text(self):

        message = 'rushingtostaveoffashortageofmedicalgradeprotectivegeartocombatthespreadofthecoronavirusminnesotaofficialsleanedonalocalcompanysglobalconnectionstoairliftacacheofmasksfromachinesefactorybacktothestatefordeliverythisweekwashingtonstatepurchasedcottonswabsforcoronavirusteststakingariskbecausetheproductlocatedbyofficialshasnotyetbeenapprovedbythefoodanddrugadministrationthestateisalsobettingthataseattlebasedoutdoorgearcompanyknownforitsbackpacksandparkascanreconfigureitsoperationstoproducen95respiratorsandcaliforniaactingasanationstateinthewordsofthegovernorbeganbuying200millionmaskspermonthtoshoreupsuppliesinthatstateandpotentiallyacrossthecountryadelsewheresomegovernorsandlawmakershavewatchedindisbeliefastheyhavesoughttoclosedealsonprecioussuppliesonlytohavethefederalgovernmentswoopintopreemptthearrangementsofficialsinonestatearesoworriedaboutthispossibilitythattheyareconsideringdispatchinglocalpoliceoreventhenationalguardtogreettwocharteredfedexplanesscheduledtoarriveinthenextweekwithmillionsofmasksfromchinaaccordingtopeoplefamiliarwiththeplanningthesepeoplewhospokeontheconditionofanonymityaskedthattheirstatenotbeidentifiedtoavoidflaggingfederalofficialstotheirshipmentasthetrumpadministrationassumeswhatthepresidenthascalledabackuproleindistributingsuppliestofightthepandemicstategovernmentsaretakingextraordinaryandoftenunorthodoxstepstocompeteinanincreasinglycutthroatglobalmarketplaceadsignupforourcoronavirusupdatesnewslettertotracktheoutbreakallstorieslinkedinthenewsletterarefreetoaccesstheresultisapatchworkandoftenchaoticscrambleforgoodspittingstatesagainsteachotherandoftenagainstothercountriesoreventheusgovernmentweredoingwhateveryoneelseisdoingohiogovmikedewinersaidinaninterviewyouvegot50statesandthefederalgovernmentallchasingthesamecompaniesitscrazysoaringpriceshaveleftstatesattimestopayupto10timesthenormalpricesforcertaingoodsaccordingtoofficialsfrommultiplestateseatingawayatcashreservesandlayingthefoundationforafiscalcrunchthatseveralgovernorsbelievewillrequirefederalbailoutswindfallssofargolargelytoforeigncompaniesthatmaketheequipmentalongwiththirdpartybrokersthatoftenhelpconnectstateswithmanufacturersandthengetacutaccordingtostateofficialsandbusinesspeopleadworriedaboutlosingpotentialdealsstategovernmentshavetossedasidelongstandingpurchasingrulesabouthowtospendtaxpayermoneyofferingfundsupfrontforequipmentbeforeitdisappearsgovernorsandtopaidesarespendinghoursonthephonehuntingforfriendsrelativesofaidesorotherpersonalconnectionsthatmightgivethemanedgeteamsofseniorstateaideswhoinnormaltimesoverseeissuessuchasclimatechangeandhealthpolicysitinconferenceroomsandbidalldaythefrenzyinvitesthepotentialforfraudaccordingtoseveralaidestogovernorswithofficialsinnewjerseyillinoismassachusettsconnecticutandwashingtonstateallsayingtheyhavebeeninundatedwithpitchesfromlikelyscamartistsohiogovmikedewineleftohiodepartmentofhealthdirectoramyactonandltgovjonhustedarriveforadailyupdateonthestatescoronavirusresponseattheohiostatehouseincolumbuslastmonthohiogovmikedewineleftohiodepartmentofhealthdirectoramyactonandltgovjonhustedarriveforadailyupdateonthestatescoronavirusresponseattheohiostatehouseincolumbuslastmonthjoshuaabickelcolumbusdispatchaphelpfromthefederalgovernmentisinconsistentwithsomegovernorshavingluckworkingwiththeirregionaldirectorsfromthefederalemergencymanagementagencyothersfindinganinwithjaredkushnerawhitehouseadviserandthepresidentssoninlawandsomeappealingdirectlytopresident'
        key = ''.join(ascii_string_to_hex_array('secret'))
        encrypted = encrypt(message, key)

        expected = decrypt(encrypted, key)

        self.assertEqual(message, expected)


if __name__ == '__main__':
    unittest.main()
