import unittest
import random
from vigenere_cracker import encrypt, int_to_hex_str, decrypt


class EncryptTest(unittest.TestCase):
    def test_big_text(self):

        plain_text = 'rushingtostaveoffashortageofmedicalgradeprotectivegeartocombatthespreadofthecoronavirusminnesotaofficialsleanedonalocalcompanysglobalconnectionstoairliftacacheofmasksfromachinesefactorybacktothestatefordeliverythisweekwashingtonstatepurchasedcottonswabsforcoronavirusteststakingariskbecausetheproductlocatedbyofficialshasnotyetbeenapprovedbythefoodanddrugadministrationthestateisalsobettingthataseattlebasedoutdoorgearcompanyknownforitsbackpacksandparkascanreconfigureitsoperationstoproducen95respiratorsandcaliforniaactingasanationstateinthewordsofthegovernorbeganbuying200millionmaskspermonthtoshoreupsuppliesinthatstateandpotentiallyacrossthecountryadelsewheresomegovernorsandlawmakershavewatchedindisbeliefastheyhavesoughttoclosedealsonprecioussuppliesonlytohavethefederalgovernmentswoopintopreemptthearrangementsofficialsinonestatearesoworriedaboutthispossibilitythattheyareconsideringdispatchinglocalpoliceoreventhenationalguardtogreettwocharteredfedexplanesscheduledtoarriveinthenextweekwithmillionsofmasksfromchinaaccordingtopeoplefamiliarwiththeplanningthesepeoplewhospokeontheconditionofanonymityaskedthattheirstatenotbeidentifiedtoavoidflaggingfederalofficialstotheirshipmentasthetrumpadministrationassumeswhatthepresidenthascalledabackuproleindistributingsuppliestofightthepandemicstategovernmentsaretakingextraordinaryandoftenunorthodoxstepstocompeteinanincreasinglycutthroatglobalmarketplaceadsignupforourcoronavirusupdatesnewslettertotracktheoutbreakallstorieslinkedinthenewsletterarefreetoaccesstheresultisapatchworkandoftenchaoticscrambleforgoodspittingstatesagainsteachotherandoftenagainstothercountriesoreventheusgovernmentweredoingwhateveryoneelseisdoingohiogovmikedewinersaidinaninterviewyouvegot50statesandthefederalgovernmentallchasingthesamecompaniesitscrazysoaringpriceshaveleftstatesattimestopayupto10timesthenormalpricesforcertaingoodsaccordingtoofficialsfrommultiplestateseatingawayatcashreservesandlayingthefoundationforafiscalcrunchthatseveralgovernorsbelievewillrequirefederalbailoutswindfallssofargolargelytoforeigncompaniesthatmaketheequipmentalongwiththirdpartybrokersthatoftenhelpconnectstateswithmanufacturersandthengetacutaccordingtostateofficialsandbusinesspeopleadworriedaboutlosingpotentialdealsstategovernmentshavetossedasidelongstandingpurchasingrulesabouthowtospendtaxpayermoneyofferingfundsupfrontforequipmentbeforeitdisappearsgovernorsandtopaidesarespendinghoursonthephonehuntingforfriendsrelativesofaidesorotherpersonalconnectionsthatmightgivethemanedgeteamsofseniorstateaideswhoinnormaltimesoverseeissuessuchasclimatechangeandhealthpolicysitinconferenceroomsandbidalldaythefrenzyinvitesthepotentialforfraudaccordingtoseveralaidestogovernorswithofficialsinnewjerseyillinoismassachusettsconnecticutandwashingtonstateallsayingtheyhavebeeninundatedwithpitchesfromlikelyscamartistsohiogovmikedewineleftohiodepartmentofhealthdirectoramyactonandltgovjonhustedarriveforadailyupdateonthestatescoronavirusresponseattheohiostatehouseincolumbuslastmonthohiogovmikedewineleftohiodepartmentofhealthdirectoramyactonandltgovjonhustedarriveforadailyupdateonthestatescoronavirusresponseattheohiostatehouseincolumbuslastmonthjoshuaabickelcolumbusdispatchaphelpfromthefederalgovernmentisinconsistentwithsomegovernorshavingluckworkingwiththeirregionaldirectorsfromthefederalemergencymanagementagencyothersfindinganinwithjaredkushnerawhitehouseadviserandthepresidentssoninlawandsomeappealingdirectlytopresident'
        key = ''.join([int_to_hex_str(k) for k in [random.randint(1, 255) for i in range(1, 9)]])
        encrypted = encrypt(plain_text, key)

        decrypted = decrypt(encrypted, key)

        self.assertEqual(plain_text, decrypted)


    def test_simple_text(self):

        expected = '0042100401110416430c071012030404'
        actual = encrypt('a secret message', ''.join([int_to_hex_str(ord(a)) for a in list('abc')]))

        self.assertEqual(expected, actual)


if __name__ == '__main__':
    unittest.main()
